tcwg/round-robin.yaml.inc: Show failures due to infra problems as UNSTABLE
Change-Id: I569308f88963bedbe2165260733ddf7ffee41485

diff --git a/tcwg_binutils.yaml b/tcwg_binutils.yaml
--- a/tcwg_binutils.yaml
+++ b/tcwg_binutils.yaml
@@ -255,7 +255,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -272,17 +272,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -470,4 +472,4 @@
           docker_arch: '{docker_arch}'
     publishers:
       - bisect-publishers
-# checksum: cf4fc505aec18bc3b124d818000f68d5
+# checksum: d88c832cbe70c79b056802b33e8fc41b
diff --git a/tcwg_bmk_ci_gnu.yaml b/tcwg_bmk_ci_gnu.yaml
--- a/tcwg_bmk_ci_gnu.yaml
+++ b/tcwg_bmk_ci_gnu.yaml
@@ -357,7 +357,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -374,17 +374,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -575,4 +577,4 @@
           job_suffix: '-tcwg_bmk_{hw}-gnu-{toolchain_ver}-{target}-{bmk}-{cflags}'
     publishers:
         - bisect-publishers
-# checksum: be6e900cc7c30eef0f51600afd707823
+# checksum: 7f55d7c33d72b35fccdf0ffeeea08b69
diff --git a/tcwg_bmk_ci_gnu_eabi.yaml b/tcwg_bmk_ci_gnu_eabi.yaml
--- a/tcwg_bmk_ci_gnu_eabi.yaml
+++ b/tcwg_bmk_ci_gnu_eabi.yaml
@@ -351,7 +351,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -368,17 +368,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -569,4 +571,4 @@
           job_suffix: '-tcwg_bmk_{hw}-gnu_eabi-{toolchain_ver}-{target}-{bmk}-{cflags}'
     publishers:
         - bisect-publishers
-# checksum: 412c0867301043eed65744d120939c37
+# checksum: 1ecd1374835b273a172dbf7a0994813a
diff --git a/tcwg_bmk_ci_llvm.yaml b/tcwg_bmk_ci_llvm.yaml
--- a/tcwg_bmk_ci_llvm.yaml
+++ b/tcwg_bmk_ci_llvm.yaml
@@ -369,7 +369,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -386,17 +386,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -590,4 +592,4 @@
           job_suffix: '-tcwg_bmk_{hw}-llvm-{toolchain_ver}-{target}-{bmk}-{cflags}'
     publishers:
         - bisect-publishers
-# checksum: 494de09b9523804827a3d13372b470ed
+# checksum: c87f4caedaf7902b3012e6a064f71d74
diff --git a/tcwg_bmk_dev_gnu.yaml b/tcwg_bmk_dev_gnu.yaml
--- a/tcwg_bmk_dev_gnu.yaml
+++ b/tcwg_bmk_dev_gnu.yaml
@@ -242,7 +242,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -259,17 +259,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -453,4 +455,4 @@
           job_suffix: ''
     publishers:
         - bisect-publishers
-# checksum: 359a5b5edf38d678971a2c38ea6f3004
+# checksum: 9f4765668ee1f1ba40a0c728332f23eb
diff --git a/tcwg_bmk_dev_llvm.yaml b/tcwg_bmk_dev_llvm.yaml
--- a/tcwg_bmk_dev_llvm.yaml
+++ b/tcwg_bmk_dev_llvm.yaml
@@ -246,7 +246,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -263,17 +263,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -458,4 +460,4 @@
           job_suffix: ''
     publishers:
         - bisect-publishers
-# checksum: 7ec671bfd5d165bad04a41f63191cb01
+# checksum: f473a58395064e7f49c3f29913a01da3
diff --git a/tcwg_cross.yaml b/tcwg_cross.yaml
--- a/tcwg_cross.yaml
+++ b/tcwg_cross.yaml
@@ -287,7 +287,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -304,17 +304,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -506,4 +508,4 @@
           job_suffix: '-{toolchain_name}-{toolchain_ver}-{target}-{type_of_test}'
     publishers:
       - bisect-publishers
-# checksum: b0cfd88ad863bd31b1469e944b589159
+# checksum: 2fb86bdf2e335e2cdc33913d97350019
diff --git a/tcwg_gcc.yaml b/tcwg_gcc.yaml
--- a/tcwg_gcc.yaml
+++ b/tcwg_gcc.yaml
@@ -269,7 +269,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -286,17 +286,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -484,4 +486,4 @@
           docker_arch: '{docker_arch}'
     publishers:
       - bisect-publishers
-# checksum: c45c1aa1e6b2e12b44379c72efbe30f8
+# checksum: 7486a5abec92760ea8d5112c4e57aa7a
diff --git a/tcwg_kernel-llvm.yaml b/tcwg_kernel-llvm.yaml
--- a/tcwg_kernel-llvm.yaml
+++ b/tcwg_kernel-llvm.yaml
@@ -296,7 +296,7 @@
             fi
 
             if [ $res != 0 ]; then
-              touch artifacts/failures
+              echo $res > artifacts/failed
             fi
 
             if [ -e artifacts/results ]; then
@@ -313,17 +313,19 @@
       - conditional-step:
           # Only run if above succeeded
           # Meaning we did not skip a bad config
-          # (a failed build is indicated by artifacts/failures)
+          # (a failed build is indicated by artifacts/failed)
           condition-kind: current-status
           steps:
             - trigger-followup-builds:
                 rr_project: '{rr_project}'
                 job_suffix: '{job_suffix}'
-            - shell: |
-                #!/bin/bash
-                if [ -f artifacts/failures ]; then
-                  exit 1
-                fi
+            - shell:
+                command: |
+                  #!/bin/bash
+                  if [ -f artifacts/failed ]; then
+                    exit $(cat artifacts/failed)
+                  fi
+                unstable-return: 125
 
 - publisher:
     name: build-publishers
@@ -514,4 +516,4 @@
           job_suffix: '-{toolchain_name}-{toolchain_ver}-{target}-{linux}-{linux_config}'
     publishers:
       - bisect-publishers
-# checksum: d96a7cadca276d1be563e608be8d5adc
+# checksum: 4e38dab45360fe40a03a8e6fa9b31706
