tcwg-benchmark: Split benchmarking into frontend and backend jobs
Change-Id: Ib37258257f7374acb13ed8354fc605597735c727

diff --git a/tcwg-benchmark.yaml b/tcwg-benchmark.yaml
--- a/tcwg-benchmark.yaml
+++ b/tcwg-benchmark.yaml
@@ -59,6 +59,7 @@
             name: bmk_hw
             choices:
               - sq
+              - stm32
               - tk1
               - tx1
             description: 'Hardware to use for benchmarking'
@@ -185,93 +186,58 @@
         - build-name:
             name: '#$BUILD_NUMBER-$displaytag'
     builders:
-      - conditional-step:
-          condition-kind: execution-node
-          nodes:
-            - tcwg-bmk-bkp-01
-          steps:
-            - shell:
-                command: |
-                  #!/bin/bash
+      - shell:
+          command: |
+            #!/bin/bash
 
-                  set -euf -o pipefail
-                  set -x
+            set -euf -o pipefail
+            set -x
 
-                  rm -rf artifacts
-                  mkdir artifacts
+            rm -rf artifacts
+            mkdir artifacts
 
-                  case "$bmk_hw:$image_arch" in
-                    sq:arm64) hw_tag=sq_64 ;;
-                    sq:armhf) hw_tag=sq_32 ;;
-                    stm32:*) hw_tag=stm32_STM32L476RGTx ;;
-                    tk1:armhf) hw_tag=tk1_32 ;;
-                    tx1:arm64) hw_tag=tx1_64 ;;
-                    tx1:armhf) hw_tag=tx1_32 ;;
-                  esac
+            case "$bmk_hw:$image_arch" in
+              sq:arm64) hw_tag=sq_64 ;;
+              sq:armhf) hw_tag=sq_32 ;;
+              stm32:armhf) hw_tag=stm32_STM32L476RGTx ;;
+              tk1:armhf) hw_tag=tk1_32 ;;
+              tx1:arm64) hw_tag=tx1_64 ;;
+              tx1:armhf) hw_tag=tx1_32 ;;
+              *)
+                echo "ERROR: Unsupported bmk_hw:image_arch: $bmk_hw:$image_arch"
+                exit 1
+                ;;
+            esac
 
-                  results_id=$(echo "$results_id" | sed \
-                                 -e "s/@build_num@/$BUILD_NUMBER/g" \
-                                 -e "s/@hw_tag@/$hw_tag/g")
+            results_id=$(echo "$results_id" | sed \
+                           -e "s/@build_num@/$BUILD_NUMBER/g" \
+                           -e "s/@hw_tag@/$hw_tag/g")
 
-                  n_boards=$(set +f; ls -tr $HOME/boards/tcwg-bmk-$bmk_hw-*.lock | wc -l)
-                  count=1
-                  while read -a bmks; do
-                    cat > artifacts/bmk-$count-parameters <<EOF
-                  bench_list=${bmks[@]}"
-                  displaytag=#$BUILD_NUMBER+$count-$displaytag
-                  bmk_node=tcwg-bmk-$bmk_hw
-                  results_id=$results_id
-                  EOF
-                    count=$(($count+1))
-                  done < <(./bmk-scripts/break-up-bmks.sh \
-                             --bench_list "$bench_list" \
-                             --bmk_hw "$bmk_hw" \
-                             --n_boards "$n_boards" \
-                             --run_profile "$run_profile")
-            - trigger-builds:
-                - project: tcwg-benchmark
-                  block: true
-                  current-parameters: true
-                  parameter-factories:
-                    - factory: filebuild
-                      file-pattern: artifacts/bmk-*-parameters
-      - conditional-step:
-          condition-kind: not
-          condition-operand:
-            condition-kind: execution-node
-            nodes:
-              - tcwg-bmk-bkp-01
-          steps:
-            - shell:
-                command: |
-                  #!/bin/bash
-
-                  set -euf -o pipefail
-                  set -x
-
-                  rm -rf artifacts
-                  mkdir artifacts
-
-                  while true; do
-                    for lock in $(set +f; ls -tr $HOME/boards/$NODE_NAME-*.lock); do
-                      (
-                        flock -en -E 123 9
-                        touch $lock
-                        NODE_NAME=$(cat <&9)
-                        export NODE_NAME
-                        exec ./jenkins-scripts/tcwg-benchmark.sh
-                      ) 9<$lock &
-                      res=0 && wait $! || res=$?
-                      if [ $res != 123 ]; then
-                        exit $res
-                      fi
-                    done
-                    sleep 30
-                  done
-                unstable-return: 125
+            n_boards=$(set +f; ls -tr $HOME/boards/tcwg-bmk-$bmk_hw-*.lock | wc -l)
+            count=1
+            while read -a bmks; do
+              cat > artifacts/bmk-$count-parameters <<EOF
+            bench_list=${bmks[@]}
+            displaytag=$BUILD_NUMBER+$count-$displaytag
+            bmk_node=tcwg-bmk-$bmk_hw
+            results_id=$results_id
+            EOF
+              count=$(($count+1))
+            done < <(./bmk-scripts/break-up-bmks.sh \
+                       --bench_list "$bench_list" \
+                       --bmk_hw "$bmk_hw" \
+                       --n_boards "$n_boards" \
+                       --run_profile "$run_profile")
+      - trigger-builds:
+          - project: tcwg-benchmark_backend
+            block: true
+            current-parameters: true
+            parameter-factories:
+              - factory: filebuild
+                file-pattern: artifacts/bmk-*-parameters
     publishers:
       - archive:
           artifacts: 'artifacts/**'
           latest-only: false
           allow-empty: true
-# checksum: 31302e41bd2d55455cbb889ce6bd3fe4
+# checksum: cd72627e2d1b9b1a1bde955b5c7442e0
