tcwg-benchmark: Retry benchmarking on HW problems
Change-Id: I326eb0efa03b9bb9f6da16b8e9f7a1daf381bf87

diff --git a/tcwg-benchmark.yaml.in b/tcwg-benchmark.yaml.in
--- a/tcwg-benchmark.yaml.in
+++ b/tcwg-benchmark.yaml.in
@@ -202,10 +202,14 @@
             rm -rf artifacts
             mkdir -p artifacts/jenkins
 
+            # Retry benchmarking once, just in case we selected a board that
+            # recently went offline.
+            retry_bmk=true
+
             while true; do
               for lock in $(set +f; ls -tr $HOME/boards/$NODE_NAME-*.lock); do
                 (
-                  flock -en -E 123 9
+                  flock -en -E 124 9
                   touch $lock
                   boardname=$(cat <&9)
                   export boardname
@@ -237,9 +241,18 @@
                   fi
                 ) 9<$lock &
                 res=0 && wait $! || res=$?
-                if [ $res != 123 ]; then
-                  exit $res
+                if [ $res != 0 ]; then
+                  if [ $res = 124 ]; then
+                    # Try to lock next board.
+                    continue
+                  elif [ $res = 125 ] && $retry_bmk; then
+                    # Failed to prepare board for benchmarking,
+                    # retry with a different board.
+                    retry_bmk=false
+                    continue
+                  fi
                 fi
+                exit $res
               done
               sleep 30
             done
